---
# This will install container dependencies, and does multi container launch with docker compose
- name: Deploy Containerized Application to EC2 instance
  hosts: all # This means to target all hosts in inventory (-i <IP>, or -i <inventory_file>)
  become: true # Everything ran as sudo

  tasks:
    # Repo prep
    - name: Update apt cache 
      # This is like running sudo apt update
      apt:
        update_cache: yes
        # Skip update if apt cache was already refreshed within the last hour (3600s) - AI recommendation
        cache_valid_time: 3600

    - name: Install Docker and Docker Compose V2
      apt:
        name:
          - docker.io
          - docker-compose-v2
        state: present

    - name: Ensure Docker service is running and enabled
      # Equivalent to 'sudo systemctl enable --now docker'
      service:
        name: docker
        state: started # Makes sure the service is running
        enabled: yes   # Ensures the service starts if reboot

    - name: Ensure target application directory exists
      # Creates the directory /opt/gitops-app on the remote host if it doesn't exist
      file:
        path: /opt/gitops-app
        state: directory
        mode: '0755' # Permissions for the directory Read/Write/Execute for owner, Read/Execute for group and others

    - name: Synchronize full application directory to remote host
    # This makes sure to transfer the backend, frontend and docker-compose.yml files
      copy:
        src: ../app/ # Local source dir relative to the playbook location
        dest: /opt/gitops-app/ # remote destination dir on the EC2 instance
        mode: '0644' # Permissions for the files Read/Write for owner, Read for group and others

    - name: Build and run the multi-container application
      # Builds container images and starts the containers in detached mode
      shell:
        cmd: docker compose up -d --build
        chdir: /opt/gitops-app # runs command in the app folder

    - name: Verify running containers
      # Queries the docker daemon to check for status of containers
      shell:
        cmd: docker ps
      register: docker_output # Puts the command stdout/stderr into a variable for later use

    - name: Display running containers
      debug:
        var: docker_output.stdout_lines