name: Terraform Automation

on:
  workflow_dispatch: # Allows manual trigger from GitHub UI
# Un comment the following lines to enable automatic trigger on push to main branch 
#  push:
#    branches:
#      - main

permissions:
  id-token: write   # Required to request the JWT token from GitHub OIDC
  contents: read    # Required to checkout code


jobs:
  terraform:
    name: Terraform Plan and Apply
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./terraform

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1

      - name: Setup Terraform CLI
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Terraform Init
        run: |
          terraform init -no-color

      - name: Terraform Plan
        env:
          TF_VAR_my_ip: ${{ secrets.MY_IP }}
          TF_VAR_public_key: ${{ secrets.EC2_PUBLIC_KEY }}
        run: |
          terraform plan -no-color

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        env:
          TF_VAR_my_ip: ${{ secrets.MY_IP }}
          TF_VAR_public_key: ${{ secrets.EC2_PUBLIC_KEY }}
        run: |
          terraform apply -auto-approve -no-color